export var ADD_TO_CART = 'ADD_TO_CART';
export var CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export var CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export var CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export var RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
//# sourceMappingURL=mutation-type.js.map